//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_version2
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int idAdmin { get; set; }
        public int idUser { get; set; }
        public string AdminRole { get; set; }
    
        public virtual user user { get; set; }
    }
}
