//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_version2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public user()
        {
            this.admins = new HashSet<admin>();
        }
    
        public int idUser { get; set; }
        [Required(ErrorMessage = "Oops Wrong userName or Password")]
        public string UserName { get; set; }
        public string userEmail { get; set; }

        [Required(ErrorMessage = "Oops Wrong userName or Password")]
        public string userpassword { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
    }
}
